/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetofinaljava;

import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author sharonhasegawa
 */
public class PanelIncluirPedido extends javax.swing.JPanel {
    private ModeloTabelaProdutos modeloTabelaProdutos = new ModeloTabelaProdutos();
    private ModeloTabelaPedidos modeloTabelaPedidos = new ModeloTabelaPedidos();
    private ModeloTabelaItemPedido modeloTabelaItens = new ModeloTabelaItemPedido();
    
    private int linhaSelecionada = -1;
    private int linhaItemSelecionada = -1;
    private Cliente clienteSelecionado;
    private Produto produtoSelecionado;
    private ItemDoPedido itemSelecionado;
    private Pedido pedido;

    /**
     * Creates new form PanelIncluirPedido
     */
    public PanelIncluirPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollProdutoPedido = new javax.swing.JScrollPane();
        tabelaProduto = new javax.swing.JTable();
        pegarCpf = new javax.swing.JTextField();
        botaoPesquisar = new javax.swing.JButton();
        exibeNomeCliente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        quantProduto = new javax.swing.JTextField();
        adicionarProduto = new javax.swing.JButton();
        scrollPedido = new javax.swing.JScrollPane();
        tabelaItens = new javax.swing.JTable();
        listaProdutos = new javax.swing.JButton();
        excluirItem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        descricaoProduto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pedidoId = new javax.swing.JLabel();

        tabelaProduto.setModel(modeloTabelaProdutos);
        tabelaProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelaProdutoMousePressed(evt);
            }
        });
        scrollProdutoPedido.setViewportView(tabelaProduto);

        botaoPesquisar.setText("Pesquisar");
        botaoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarActionPerformed(evt);
            }
        });

        jLabel1.setText("Produto");

        adicionarProduto.setText("Adicionar");
        adicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarProdutoActionPerformed(evt);
            }
        });

        tabelaItens.setModel(modeloTabelaItens);
        scrollPedido.setViewportView(tabelaItens);

        listaProdutos.setText("Listar Produtos");
        listaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaProdutosActionPerformed(evt);
            }
        });

        excluirItem.setText("Excluir Item");
        excluirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirItemActionPerformed(evt);
            }
        });

        jLabel2.setText("CPF do cliente");

        jLabel3.setText("Quantidade");

        jLabel4.setText("Produtos disponíveis");

        jLabel5.setText("Itens do pedido:");

        jLabel6.setText("Cliente:");

        jLabel7.setText("Pedido ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(24, 24, 24)
                                .addComponent(listaProdutos))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(scrollProdutoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(descricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(quantProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(adicionarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 36, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(exibeNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pedidoId, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(excluirItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(scrollPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pegarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoPesquisar)
                    .addComponent(pegarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(listaProdutos)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(exibeNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pedidoId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(19, 19, 19)))
                        .addComponent(jLabel5)
                        .addGap(5, 5, 5)
                        .addComponent(scrollPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                    .addComponent(scrollProdutoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(excluirItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(quantProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(adicionarProduto)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaProdutoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutoMousePressed
        try {
            linhaSelecionada = tabelaProduto.rowAtPoint(evt.getPoint());
            produtoSelecionado = modeloTabelaProdutos.getProduto(linhaSelecionada);
            descricaoProduto.setText(produtoSelecionado.getDescricao());
            quantProduto.setText("1");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(tabelaProduto, e.getMessage());
        }
    }//GEN-LAST:event_tabelaProdutoMousePressed

    private void botaoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarActionPerformed
        String cpf = pegarCpf.getText();
        if (cpf.isEmpty()) return;
        
        try {
            ClienteDAO dao = new ClienteDAO();
            clienteSelecionado = dao.get(cpf);

            String nome = clienteSelecionado.getNome();
            String sobrenome = clienteSelecionado.getSobrenome();

            exibeNomeCliente.setText(nome + " " + sobrenome);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(tabelaProduto, e.getMessage());
        }
    }//GEN-LAST:event_botaoPesquisarActionPerformed

    private void adicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarProdutoActionPerformed
        if (produtoSelecionado == null || clienteSelecionado == null) return;
        
        PedidoDAO pedidoDao = new PedidoDAO();
        ItemDoPedidoDAO itemDao = new ItemDoPedidoDAO();
        
        try {
            Produto produto = modeloTabelaProdutos.getProduto(linhaSelecionada);            ;
            long quantidade = Long.parseLong(quantProduto.getText());
            LocalDate data = LocalDate.now();

            if (pedido == null) {
                pedido = new Pedido(data, clienteSelecionado, null);
                pedidoDao.insere(pedido);
                
                pedidoId.setText(Long.toString(pedido.getId()));
            }

            ItemDoPedido item = new ItemDoPedido(quantidade, produto);
            itemDao.insere(pedido.getId(), item);

            if (modeloTabelaItens.getRowCount() == 0) {
                List<ItemDoPedido> lista = itemDao.getLista(pedido.getId());
                modeloTabelaItens.setListaItens(lista);
            } else {
                modeloTabelaItens.adicionaItem(item);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(tabelaProduto, e.getMessage());
        }
    }//GEN-LAST:event_adicionarProdutoActionPerformed

    private void listaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaProdutosActionPerformed
        try {
            List<Produto> lista = new ProdutoDAO().getLista();
            modeloTabelaProdutos.setListaProdutos(lista);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(tabelaProduto, e.getMessage());
        }
    }//GEN-LAST:event_listaProdutosActionPerformed

    private void excluirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirItemActionPerformed
        if (itemSelecionado == null) return;
        
        ItemDoPedidoDAO dao = new ItemDoPedidoDAO();
        try {
            dao.deleta(pedido.getId(), itemSelecionado);
            modeloTabelaItens.removeItem(itemSelecionado);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(tabelaProduto, e.getMessage());
        }
    }//GEN-LAST:event_excluirItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarProduto;
    private javax.swing.JButton botaoPesquisar;
    private javax.swing.JLabel descricaoProduto;
    private javax.swing.JButton excluirItem;
    private javax.swing.JLabel exibeNomeCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton listaProdutos;
    private javax.swing.JLabel pedidoId;
    private javax.swing.JTextField pegarCpf;
    private javax.swing.JTextField quantProduto;
    private javax.swing.JScrollPane scrollPedido;
    private javax.swing.JScrollPane scrollProdutoPedido;
    private javax.swing.JTable tabelaItens;
    private javax.swing.JTable tabelaProduto;
    // End of variables declaration//GEN-END:variables
}
