/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetofinaljava;

import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author sharonhasegawa
 */
public class PanelListarPedido extends javax.swing.JPanel {
    private ModeloTabelaItemPedido modeloTabelaItens = new ModeloTabelaItemPedido();
    private ModeloTabelaPedidos modeloTabelaPedidos = new ModeloTabelaPedidos();
    
    private Cliente clienteSelecionado;
    private Pedido pedidoSelecionado;

    /**
     * Creates new form PanelListarPedido
     */
    public PanelListarPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listaPedidos = new javax.swing.JButton();
        scrollPedidos = new javax.swing.JScrollPane();
        tabelaPedidos = new javax.swing.JTable();
        cpfCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaItens = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nomeClienteSelecionado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pedidoId = new javax.swing.JLabel();

        listaPedidos.setText("Listar pedidos");
        listaPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaPedidosActionPerformed(evt);
            }
        });

        tabelaPedidos.setModel(modeloTabelaPedidos);
        tabelaPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelaPedidosMousePressed(evt);
            }
        });
        scrollPedidos.setViewportView(tabelaPedidos);

        jLabel2.setText("CPF do cliente");

        tabelaItens.setModel(modeloTabelaItens);
        jScrollPane1.setViewportView(tabelaItens);

        jLabel1.setText("Cliente");

        jLabel3.setText("Pedidos do cliente");

        jLabel4.setText("Itens do pedido");

        jLabel5.setText("Pedido ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(241, 241, 241)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pedidoId, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listaPedidos))
                            .addComponent(nomeClienteSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaPedidos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeClienteSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pedidoId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                    .addComponent(scrollPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listaPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaPedidosActionPerformed
        try {
            String cpf = cpfCliente.getText();
            if (cpf.isEmpty()) return;
            
            PedidoDAO dao = new PedidoDAO();
            ClienteDAO clienteDao = new ClienteDAO();
            
            List<Pedido> lista = dao.getListaPorCliente(cpf);
            clienteSelecionado = clienteDao.get(cpf);

            String nome = clienteSelecionado.getNome() + " " + clienteSelecionado.getSobrenome();
            nomeClienteSelecionado.setText(nome);
            
            modeloTabelaPedidos.setListaPedidos(lista);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(tabelaPedidos, e.getMessage());
        }
    }//GEN-LAST:event_listaPedidosActionPerformed

    private void tabelaPedidosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPedidosMousePressed
        try {
            int linha = tabelaPedidos.rowAtPoint(evt.getPoint());
            pedidoSelecionado = modeloTabelaPedidos.getPedido(linha);
            pedidoId.setText(Long.toString(pedidoSelecionado.getId()));

            ItemDoPedidoDAO dao = new ItemDoPedidoDAO();
            List<ItemDoPedido> itens = dao.getLista(pedidoSelecionado.getId());

            modeloTabelaItens.setListaItens(itens);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(tabelaPedidos, e.getMessage());
        }
    }//GEN-LAST:event_tabelaPedidosMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cpfCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listaPedidos;
    private javax.swing.JLabel nomeClienteSelecionado;
    private javax.swing.JLabel pedidoId;
    private javax.swing.JScrollPane scrollPedidos;
    private javax.swing.JTable tabelaItens;
    private javax.swing.JTable tabelaPedidos;
    // End of variables declaration//GEN-END:variables
}
