package projetofinaljava;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JTextField;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author levyc
 */
public class TelasSistema extends javax.swing.JFrame {

    private ModeloTabelaProdutos modeloTabela = new ModeloTabelaProdutos();
    private int linhaSelecionada=-1;

    /**
     * Creates new form NovaTabelaProduto
     */
    public TelasSistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botaoNovoProduto = new javax.swing.JButton();
        descricaoLabel = new javax.swing.JLabel();
        caixaDeTextoDescricao = new javax.swing.JTextField();
        scrollPanelTabela = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        listarProdutos = new javax.swing.JButton();
        excluirProduto = new javax.swing.JButton();
        editarProduto = new javax.swing.JButton();
        limparTabela = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botaoNovoProduto.setText("Novo");
        botaoNovoProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoNovoProdutoMouseClicked(evt);
            }
        });
        botaoNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoProdutoActionPerformed(evt);
            }
        });

        descricaoLabel.setText("Descrição: ");

        caixaDeTextoDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaDeTextoDescricaoActionPerformed(evt);
            }
        });

        tabela.setModel(modeloTabela);
        scrollPanelTabela.setViewportView(tabela);

        listarProdutos.setText("Listar");
        listarProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listarProdutosMouseClicked(evt);
            }
        });
        listarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarProdutosActionPerformed(evt);
            }
        });

        excluirProduto.setText("Excluir");
        excluirProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excluirProdutoMouseClicked(evt);
            }
        });
        excluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirProdutoActionPerformed(evt);
            }
        });

        editarProduto.setText("Editar (NA)");
        editarProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarProdutoMouseClicked(evt);
            }
        });
        editarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarProdutoActionPerformed(evt);
            }
        });

        limparTabela.setText("Limpar");
        limparTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limparTabelaMouseClicked(evt);
            }
        });
        limparTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparTabelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPanelTabela, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoNovoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(listarProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(descricaoLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(caixaDeTextoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editarProduto))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(excluirProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(limparTabela)
                                .addGap(27, 27, 27)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listarProdutos)
                    .addComponent(excluirProduto)
                    .addComponent(limparTabela))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descricaoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caixaDeTextoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoNovoProduto)
                    .addComponent(editarProduto))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoNovoProdutoActionPerformed

    private void botaoNovoProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoNovoProdutoMouseClicked
            String descricao = caixaDeTextoDescricao.getText();
            Produto p = new Produto(0L, descricao);
            ProdutoDAO dao = new ProdutoDAO();
            dao.insere(p);
            modeloTabela.adicionaProduto(p);      
        

    }//GEN-LAST:event_botaoNovoProdutoMouseClicked

    private void caixaDeTextoDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaDeTextoDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaDeTextoDescricaoActionPerformed

    private void listarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarProdutosActionPerformed

    private void listarProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarProdutosMouseClicked
        List<Produto> lista = new ProdutoDAO().getLista();
        modeloTabela.setListaProdutos(lista);

    }//GEN-LAST:event_listarProdutosMouseClicked

    private void excluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirProdutoActionPerformed
        ProdutoDAO p = new ProdutoDAO();
        int[] linhasSelecionadas = tabela.getSelectedRows();
        List<Produto> listaExcluir = new ArrayList();
        for (int i = 0; i < linhasSelecionadas.length; i++) {
            Produto produto = modeloTabela.getProduto(linhasSelecionadas[i]);
            p.deleta(produto);
            listaExcluir.add(produto);

        }
        for (Produto produto : listaExcluir) {
            modeloTabela.deleteProduto(produto);
        }    

    }//GEN-LAST:event_excluirProdutoActionPerformed

    private void editarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarProdutoActionPerformed

    private void excluirProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluirProdutoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_excluirProdutoMouseClicked

    private void editarProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarProdutoMouseClicked
       if (linhaSelecionada !=-1) {
            Produto produto = modeloTabela.getProduto(linhaSelecionada);
            produto.setDescricao(caixaDeTextoDescricao.getText());
            ProdutoDAO dao = null;            
            dao = new ProdutoDAO();
            dao.atualiza(produto);

            modeloTabela.fireTableRowsUpdated(linhaSelecionada, linhaSelecionada);
       }


    }//GEN-LAST:event_editarProdutoMouseClicked

    private void limparTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparTabelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limparTabelaActionPerformed

    private void limparTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limparTabelaMouseClicked
        modeloTabela.limparTabela();
    }//GEN-LAST:event_limparTabelaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelasSistema.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelasSistema.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelasSistema.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelasSistema.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelasSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoNovoProduto;
    private javax.swing.JTextField caixaDeTextoDescricao;
    private javax.swing.JLabel descricaoLabel;
    private javax.swing.JButton editarProduto;
    private javax.swing.JButton excluirProduto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limparTabela;
    private javax.swing.JButton listarProdutos;
    private javax.swing.JScrollPane scrollPanelTabela;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
